name: Net-DNS-ValueDomain-DDNS
version: 0.01
license: perl
distribution_type: module
requires:
  LWP::UserAgent: 0
recommends:
  Crypt::SSLeay: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
